- .applatix/axscm_checkout.yaml
- .applatix/rocksdb-build.yaml
- build_tools/ax_build.sh
- add auto-build policy
- increase axscm_checkout cpu/memory allocation
> Applatix integration: add auto-build policy

- cloud/aws/aws_s3.cc
`GetFileSize` tries to read 0 bytes, but, because of an off-by-one error, ends up reading the whole file.
Also, avoid 2 unnecessary copies in the file path. (There were 3 copies before: one from AWS's iostream's rdbuf into our stringstream, one from our stringstream into a temporary string, one from the temporary string into the scratch buffer; now there is only one, directly from AWS's iostream into the scratch buffer).
> Read 0 bytes from S3 correctly; avoid 2 copies in read path.

- cloud/aws/aws_env.cc
- cloud/aws/aws_env.h
- cloud/aws/aws_file.h
- cloud/aws/aws_kinesis.cc
- cloud/aws/aws_kinesis.h
- cloud/aws/aws_log.cc
- cloud/aws/aws_log.h
- cloud/aws/aws_s3.cc
- cloud/cloud_env.cc
- cloud/cloud_env_impl.h
- cloud/cloud_env_wrapper.h
- db/db_test_util.cc
- env/env_basic_test.cc
- include/rocksdb/cloud/cloud_env_options.h
- src.mk
- tools/db_bench_tool.cc
Introducing `CloudLogController` which abstracts cloud-based WAL interaction, both for appending and tailing. `KinesisController` (previously known as `KinesisSystem`) inherits `CloudLogController`, and implements AWS Kinesis-specific stream interaction logic.
> Refactored AWS Kinesis-based cloud WAL

- cloud/aws/aws_env.cc
- cloud/aws/aws_env.h
- cloud/aws/aws_kinesis.cc
- cloud/aws/aws_kinesis.h
- cloud/aws/aws_log.cc
- cloud/aws/aws_log.h
- cloud/cloud_env.cc
- cloud/cloud_env_impl.h
- cloud/cloud_env_options.cc
- cloud/cloud_env_wrapper.h
- cloud/db_cloud_impl.cc
- cloud/db_cloud_test.cc
- include/rocksdb/cloud/cloud_env_options.h
Kinesis-based WAL storing test had a logical error. I've fixed the error and disabled the test temporarily since it's now failing.
> Fixed Kinesis-based WAL storing test

- cloud/aws/aws_env.cc
- cloud/aws/aws_env.h
We don't want to create a separate thread for each AwsEnv.
> [AwsEnv] Execute delayed file deletion in a singleton JobExecutor

- cloud/LANGUAGE-BINDINGS.md
> add link to erlang binding

- cloud/aws/aws_env.cc
- cloud/aws/aws_file.h
- cloud/cloud_env_impl.h
- cloud/db_cloud_test.cc
This changeset addresses the build issues while trying to compile RocksDB-Cloud on a MaC.
> Changes to get rocksdb-cloud to build on Mac

- cloud/aws/aws_env.cc
- cloud/aws/aws_env.h
- cloud/cloud_env.cc
- cloud/db_cloud_impl.cc
- include/rocksdb/cloud/cloud_env_options.h
Replaces checks that were not consistent throughout the codebase.
> Add HasXXXBucket Methods

- cloud/aws/aws_env.h
- db/compaction/compaction_job.cc
- db/db_impl/db_impl.h
- include/rocksdb/utilities/stackable_db.h
Problems with methods not being marked as override, and one issue with type casting.
> Address Build Issues on Mac OSX

- docker/Dockerfile
Update `Dockerfile` to Ubuntu 18.04. I ran locally and it works.
> Update Dockerfile to ubuntu 18.04

- run_tests.sh
This script uses the docker image to run all the necessary tests.
> Add a run_tests.sh script

- cloud/aws/aws_env.cc
- cloud/aws/aws_env.h
- cloud/aws/aws_s3.cc
- cloud/cloud_scheduler.cc
- cloud/cloud_scheduler.h
- cloud/cloud_scheduler_test.cc
- cloud/cloud_storage_provider.cc
- cloud/db_cloud_test.cc
- cloud/remote_compaction_test.cc
- db/db_impl/db_impl_remote_compaction.cc
- db/db_test_util.cc
- tools/db_bench_tool.cc
Fixed the cloud build to successfully build when LITE=1 and to build the unity_test.  
Made more of the tests pass COMPILE_WITH_TSAN, though db_cloud_test does not currently pass (requires much more investigation).
> Make Cloud work for LITE and Unity tests

- cloud/aws/aws_env.cc
- cloud/aws/aws_s3.cc
- cloud/cloud_storage_provider_impl.h
- include/rocksdb/cloud/cloud_env_options.h
- include/rocksdb/cloud/cloud_storage_provider.h
This allows a user to override the default S3 Storage Provider if desired.
> Allow configuring the storage provider from the public API.

- cloud/cloud_env_options.cc
- cloud/cloud_file_cache.cc
- cloud/cloud_storage_provider.cc
Log additional debug messages for sst_file_cache size usage.
> Debug message when bucket is not found.

- cloud/aws/aws_s3.cc
POSIX allows an error from write to be reported late, at close
time. Check close status before declaring the GetObject operation as
success.
> Check file close status in GetObject

- cloud/cloud_env_impl.cc
- cloud/cloud_env_impl.h
- cloud/filename.h
- cloud/manifest_reader.cc
- cloud/manifest_reader.h
- include/rocksdb/cloud/cloud_env_options.h
Provide the interface to find all lives so that we can access it from our codepath directly. 
Will add tests later once the tool is implemented. Of course, I'll test this part with the tool implemented.
> Get list of live files through CloudEnv

- cloud/cloud_env_impl.cc
- cloud/cloud_env_impl.h
- cloud/cloud_env_wrapper.h
- cloud/db_cloud_test.cc
- cloud/manifest_reader.cc
- cloud/manifest_reader.h
- include/rocksdb/cloud/cloud_env_options.h
> Fix CloudEnvImpl::FindAllLiveFiles

- db/version_edit.h
> Fix comment about replication sequence

- cloud/db_cloud_test.cc
- cloud/manifest_reader.cc
When a CF is dropped, the files are not marked as delete in Manifest. Updated `GetLiveFiles`  to exclude files of dropped CF.
Currently, only the background `purger` is using this function and it has never been enabled. So changing the logic of this function should be fine.
> Files of dropped CF should not be included in live files

- cloud/db_cloud_test.cc
- cloud/manifest_reader.cc
Fixed the bug that files moved across levels are not listed as live files. For example:
```
VersionEdit {
PrevLogNumber: 0
NextFileNumber: 67
LastSeq: 50
DeleteFile: 0 6
AddFile: 6 6 1506 ...
ColumnFamily: 0
}
```
In this version edit, file number: 6 of CF 0 is moved from level 0 to level 6.
> files moved across levels should be listed as live files

- Makefile
Internal test: https://buildkite.com/rockset/build-everything/builds/59763#_
> RocksDB-Cloud can compile with system folly

- cloud/cloud_env_impl.cc
Tried to maintain the same behavior as `ephemeral_resync_on_open` here. This is temporary while we rollout this change. Once we are confident that the change is safe by checking the log, we can remove this piece of code.
> force resync_on_open when src bucket matches dest bucket

- Makefile
- cloud/cloud_env_test.cc
- cloud/cloud_manifest_test.cc
- db/db_test.cc
Some of the recent leader/follower changes broke existing tests. Fixed it here.
Also, added a build target `rocksdb_cloud_all` to build everything for rocksdb-cloud.
> Fix failing tests

- cloud/cloud_env_impl.cc
`GetStorageProvider()->NewCloudWritableFile` might fail, which would cause the `f` to be `nullptr`.
> [SYS-3225] check return status of NewCloudWritableFile

- cloud/cloud_env_impl.cc
- cloud/cloud_env_impl.h
- cloud/db_cloud_test.cc
- include/rocksdb/cloud/cloud_env_options.h
We would like to disable invisible file deletion from s3 when db is opened in follower mode and only delete these files from s3 when follower tries to take over as leader. Local invisible files will still be deleted
> [SYS-3286] Added an option to disable cloud invisible file deletion on db open

- cloud/replication_test.cc
- db/db_impl/db_impl_write.cc
Our codepath SwitchMemtableWithoutCreatingWAL() missed one piece from
SwitchMemtable() - advancing empty CF's log file numbers. This resulted in all
log files being retained forever, which is not a big problem given that we are
not using WAL and only creating a new log file on every DB::Open(). We should
fix anyway.
This PR just copies the relevant logic from SwitchMemtable():
https://github.com/rockset/rocksdb-cloud/blob/914d9321d9b605969ef1821af4218c5e27e79a99/db/db_impl/db_impl_write.cc#L2213-L2223
Unit test is added.
> [SYS-3382] Advance log number for empty column families when switching memtable

- cloud/cloud_file_deletion_scheduler.cc
- cloud/cloud_file_deletion_scheduler.h
- cloud/cloud_file_system.cc
- cloud/cloud_file_system_impl.cc
- cloud/db_cloud_test.cc
- include/rocksdb/cloud/cloud_file_system.h
Added new option to specify file deletion delay.
> [sys-4000] add option to specify file deletion delay

- cloud/cloud_file_system_impl.cc
- cloud/cloud_file_system_impl.h
- include/rocksdb/cloud/cloud_file_system.h
Summary:
This will be useful for debugging SYS-4410
Test Plan:
Reviewers:
> [SYS-4410] Expose GetMaxFileNumberFromCurrentManifest

- cloud/replication_test.cc
- db/memtable_list.cc
Summary:
We have a bug in a scenario where:
1/ Multiple column families are flushed with atomic flush, 2/ not all column families being flushed have the same number of memtables, and
3/ at least one column family is flushing more than one memtable.
In that case, we might end up with a wrong replication sequence on recovery.
This is because VersionEdit of each CF in atomic flush will persist its own replication sequence. If one CF didn't receive any writes since last SwithMemtable, its replication sequence might be smaller than a replication sequence of another CF in the same flush.
The rules for applying replication sequence in recovery is last-update-wins, so if the column family with an earlier replication sequence is written to MANIFEST last, its replication sequence would win, even …
> [SYS-4535] Fix replication sequence edge case

- cloud/replication_test.cc
- db/db_impl/db_impl.cc
For current way of setting log number when applying manifest write, the log number could go backwards. Considering following sequence of events:
* kMemtableSwitch with log number L 
* kMemtableSwitch with log number L+1
* kManifestWrite with log number L (related to the first memtable switch)
If this is a follower and it takes over right after applying the manifest write, the alive log number will go backwards and be smaller than `min_log_number_to_keep`. This will cause all log numbers in `alive_log_files_` to be pruned.
So we should only set the log number if it's strictly greater than existing alive log number. We don't need to do this for memtable switch though. Memtable switch should never set it to smaller value.
> [sys-4930] log number shouldn't go backwards

- cloud/remote_compaction_test.cc
`TEST_SetFileDeletionDelay` has been removed. But I forgot to remove it from `remote_compaction_test`
> remove references of deleted function TEST_SetFileDeletionDelay

- cloud/replication_test.cc
- db/db_impl/db_impl.cc
- db/db_impl/db_impl.h
- db/version_edit.h
- include/rocksdb/db.h
- include/rocksdb/status.h
- util/status.cc
Follow up for: https://github.com/rockset/rocksdb-cloud/pull/277
We've been running with epoch number replication for weeks. Time to delete the unnecessary hacky code.
> Remove epoch calculation code

- cloud/db_cloud_test.cc
Adding cloud/cloud_manifest.h to cloud/db_cloud_test.cc to fix compilation.
> Add missing include.

- table/multiget_context.h
Switching to using std::bitset for tracking various request states
(complted/skipped/invalid) in MultiGetContext and bumping the
MAX_BATCH_SIZE to 128. This is needed to increase parallelism of
MultiGet fetches in distributed environment.
> Increase MAX_BATCH_SIZE to 128 in MultiGetContext.

- db/db_impl/db_impl.cc
- db/version_edit.cc
Summary:
We seem to have lost
https://github.com/rockset/rocksdb-cloud/pull/130/files when we pulled
latest RocksDB.
Test Plan:
Internal test
Reviewers:
> [SYS-7551] Don't use options file

- cloud/replication_test.cc
- db/db_impl/db_impl.cc
- db/db_impl/db_impl.h
- db/db_test.cc
- include/rocksdb/db.h
- include/rocksdb/utilities/stackable_db.h
Epoch based divergence detection has been rolled out for a few months. Time to cleanup the code to support rolling out.
> rollout epoch based divergence

- cloud/cloud_file_system.cc
- include/rocksdb/cloud/cloud_file_system.h
Summary:
See https://github.com/rockset/rs/pull/24132#discussion_r1401179422
Test Plan:
Internal test
Reviewers:
> [SYS-7856] Allow empty prefix in RocksDB-Cloud

- cloud/aws/aws_s3.cc
- cloud/cloud_file_system_impl.cc
- cloud/cloud_storage_provider.cc
- include/rocksdb/cloud/cloud_file_system.h
- include/rocksdb/cloud/cloud_file_system_impl.h
- include/rocksdb/cloud/cloud_file_system_wrapper.h
- include/rocksdb/cloud/cloud_storage_provider.h
- include/rocksdb/cloud/cloud_storage_provider_impl.h
Updated `CloudFileSystemImpl::CopyLocalFileToDest` and `PutCloudObject` to accept an optional md5_checksum parameter
> [MISC] Support md5 checksum
