- .applatix/axscm_checkout.yaml
- .applatix/rocksdb-build.yaml
- build_tools/ax_build.sh
- docker/Dockerfile
As discussed with Dhruba, this is to configure automated builds with Applatix (in addition to Travis).
- add docker/Dockerfile to build docker image used in Applatix environment.
- add build_tools/ax_build.sh to be triggered by Applatix workflow rocksdb-build.yaml
This script is pretty primitive for now.
- add .applatix/rocksdb-build.yaml that specifies the Applatix build/test workflow
This workflow is just one sample Applatix workflow.
- add .applatix/axscm_checkout.yaml which is a utility yaml used in Applatix build/test workflow to checkout source tree
> Initial Applatix integration

- .applatix/rocksdb-build.yaml
add termination_policy to rocksdb-build.yaml, so a job won't last more than 2 hours and cost more than $1.
> add termination_policy to rocksdb-build.yaml

- cloud/aws/aws_env.h
- cloud/cloud_env_wrapper.h
- table/partitioned_filter_block_test.cc
I am trying to get baseline clean compilation working on my Mac OS X dev box. For this setting, it's just git clone then "make clean all".  Note that I did not set USE_AWS, as I plan to add Azure block support. 
For aws_env.h, I probably made more formatting changes because adding the extra "override" keywords killed the original indentation. So I had to apply "clang-format", which I thought is RocksDB code formatting standard. Let me know so I can reduce the changeset, 
The std::max issue is that clang is picky on the two params to be of the exact types.
> fix build issues with clang/OSX

- README.md
This small PR updates the Travis Build Status in README to `rocksdb-cloud`, instead of the original `rocksdb` link.
> Updated Travis Build Status in README.

- README.md
Per [comment](https://github.com/rockset/rocksdb-cloud/pull/29#issuecomment-338509583), I added a link to `Applatix` build logs. Unfortunately, I did not find an image link similar to `Travis` build status.
Any format suggestions will be appreciated.
> Added Applatix build link.

- cloud/cloud_env_impl.h
Without it, CloudEnvImpl uses Env::GetThreadList(), which returns Status::NotSupported.
> Implement CloudEnvImpl::GetThreadList which redirects the call base_env_

- cloud/aws/aws_env.cc
- cloud/aws/aws_env.h
- cloud/aws/aws_file.h
- cloud/aws/aws_kafka.cc
- cloud/aws/aws_kinesis.cc
- cloud/aws/aws_kinesis.h
- cloud/aws/aws_log.cc
- cloud/aws/aws_s3.cc
- cloud/cloud_env.cc
- cloud/cloud_env_wrapper.h
- cloud/db_cloud_impl.cc
- cloud/db_cloud_test.cc
- cloud/purge.cc
- db/db_test_util.cc
- include/rocksdb/cloud/cloud_env_options.h
- tools/db_bench_tool.cc
The XXXGetBucketPrefix methods were changed to XXXGetBucketName.  Whereas the old methods would return a name and the "GetBucketName" methods (of aws_file) would prepend "rockset." to the name, the new methods return the full name.  
Additionally, environment variables were added/changed to set the PREFIX (to use a value instead of "rockset.").
The impetus for this change was because we cannot specify the name of the buckets in our environment to be prefixed by "rockset.".  Because the GetBucketName methods were not part of a class, it was hard to override the settings.  Additionally, this change will make it easier for other cloud environments to use the same methodology in the future.
> Change BucketPrefix methods to BucketName

- cloud/aws/aws_env.cc
- cloud/aws/aws_env.h
- cloud/aws/aws_s3.cc
- cloud/cloud_env.cc
- cloud/cloud_env_impl.h
- cloud/cloud_env_wrapper.h
- include/rocksdb/cloud/cloud_env_options.h
Eliminates the need for some virtual methods and cleans up some of the code.
> Make CloudEnvOptions a member variable of CloudEnv

- cloud/aws/aws_env.cc
- cloud/aws/aws_env.h
- cloud/aws/aws_log.cc
- cloud/aws/aws_s3.cc
- cloud/cloud_env_impl.cc
- cloud/cloud_env_impl.h
- cloud/cloud_env_wrapper.h
- cloud/db_cloud_impl.cc
- include/rocksdb/cloud/cloud_env_options.h
1. Move the info_log into the CloudEnv class so that there is only one of them. Right now there is one in CloudEnvImpl and AwsEnv. This change makes there be only one of them and eliminates any duplication and confusion.
2. Move the AWS-related options into a common struct, instead of fields within the CloudEnvOptions. This makes it possible to remove them as a unit from the CloudEnvOptions in the future if so desired (which would be a very good thing).
3. Make GetBaseEnv part of CloudEnv and remove it and the duplications from CloudEnvImpl (where there was also a GetPosixEnv that did the exact same thing).
> Unify Info_log and options

- cloud/examples/clone_example.cc
- cloud/examples/cloud_dump.cc
- cloud/examples/cloud_durable_example.cc
Hello and thank you for RocksDB-Cloud,
These are changes I needed to make to get the cloud examples more easily working with an AWS S3 bucket that did not start with the default bucket prefix "rockset.".
I thought they might be useful for anyone else wanting to try them out on a bucket not starting with "rockset.".
> Show in the cloud examples how to use bucket other than with prefix "rockset."

- cloud/aws/aws_s3.cc
Fix issue https://github.com/rockset/rocksdb-cloud/issues/73
Code in S3ReadableFile::GetUniqueId() is wrong, instead of
if (max_size < kMaxVarint64Length && file_number > 0)
it should be
if (max_size >= kMaxVarint64Length && file_number > 0) {
Tesging done:
Works in my local build - no more asserts in debug build.
> Fix assert/data corruption when using persistent cache

- cloud/aws/aws_env.cc
- cloud/aws/aws_env.h
- cloud/aws/aws_kafka.cc
- cloud/aws/aws_kinesis.cc
- cloud/aws/aws_s3.cc
- cloud/cloud_env_impl.cc
- cloud/cloud_env_impl.h
- cloud/cloud_log_controller.cc
- cloud/cloud_log_controller_impl.h
- cloud/cloud_storage_provider.cc
- cloud/cloud_storage_provider_impl.h
- cloud/db_cloud_test.cc
- include/rocksdb/cloud/cloud_log_controller.h
- include/rocksdb/cloud/cloud_storage_provider.h
Make the construction of the Cloud objects (LogController, CloudEnv, and StorageProvider) be a separate step from the configuration of the objects and the initialization.  This will later allow the objects to be configured and initialized via properties files.
> Separate out the configuration from initialization and construction

- cloud/aws/aws_env.cc
- cloud/aws/aws_s3.cc
- cloud/cloud_env_impl.cc
- cloud/cloud_env_wrapper.h
- cloud/cloud_storage_provider.cc
- cloud/cloud_storage_provider_impl.h
- cloud/db_cloud_impl.cc
- cloud/db_cloud_test.cc
- cloud/purge.cc
- include/rocksdb/cloud/cloud_storage_provider.h
This rename is to minimize the conflicts on some platforms (like Windows) with built-in names (like GetObject).
> Rename the XXObject methods to XXCloudObject

- cloud/aws/aws_env.cc
- cloud/aws/aws_env.h
- cloud/aws/aws_file.h
- cloud/aws/aws_kafka.cc
- cloud/aws/aws_kinesis.cc
- cloud/aws/aws_retry.cc
- cloud/aws/aws_s3.cc
- cloud/cloud_env.cc
- cloud/cloud_env_impl.cc
- cloud/cloud_env_impl.h
- cloud/cloud_env_options.cc
- cloud/cloud_log_controller.cc
- cloud/cloud_log_controller_impl.h
- cloud/cloud_manifest.cc
- cloud/cloud_manifest.h
- cloud/cloud_manifest_test.cc
- cloud/cloud_storage_provider_impl.h
- cloud/db_cloud_impl.cc
- cloud/db_cloud_impl.h
- cloud/db_cloud_test.cc
- cloud/filename.h
- cloud/manifest_reader.cc
- cloud/purge.h
- db/db_test_util.cc
- db/db_test_util.h
- include/rocksdb/cloud/cloud_env_options.h
- include/rocksdb/cloud/db_cloud.h
With the addition of the CloudStorageProvider and CloudLogController, much of the Env methods were no longer specific to AWS.  This PR moves most of these methods into the CloudEnvImpl class, so that other cloud platforms need to implement fewer methods.
Note that Env::DeleteFile was not moved as part of this PR.  DeleteFile has more infrastructure around it and will be moved in a separate PR.
> Move common code from AwsEnv to CloudEnvImpl

- cloud/cloud_env.cc
- cloud/cloud_env_impl.cc
- cloud/cloud_env_impl.h
There were a lot of places where the code would make two calls into the StorageProvider -- one for the dest bucket and one for source.  Some -- but not all -- of the calls were guarded by a "SrcMatchesDest" check to prevent an extra call.  This checkin moves most of the calls into a single method that will check the two buckets and perform the proper checks.
Also, makes sure the storage provider and log controller are deleted prior to the cloud env completely being deleted.  This can help guard against some cases where the provider attempts to access some cloud env resources during detruction.
> Clean up use of StorageProvider

- db/compaction/compaction_job.cc
- include/rocksdb/pluggable_compaction.h
We create V2 of the interfaces for `PluggableCompactionService` which adds `Context` parameter. Right now this context only contains `shutting_down` variable, which allows clients to short circuit the remote compaction if we try to close the DB.
> Add shutting_down signal to remote compaction

- cloud/aws/aws_s3.cc
- cloud/db_cloud_test.cc
Reported by https://github.com/rockset/rocksdb-cloud/pull/101. Since I haven't received the SLA signed, I'll just make this PR instead.
Test plan: turn on `use_aws_transfer_manager` in the test and the test will fail without this patch.
> Fix a bug in PutCloudObject when using transfer manager

- cloud/aws/aws_env.cc
- cloud/aws/aws_env.h
- cloud/aws/aws_kafka.cc
- cloud/aws/aws_kinesis.cc
- cloud/aws/aws_retry.cc
- cloud/aws/aws_s3.cc
- cloud/cloud_env_impl.cc
- cloud/cloud_env_impl.h
- cloud/cloud_log_controller.cc
- cloud/cloud_storage_provider.cc
- cloud/cloud_storage_provider_impl.h
- cloud/db_cloud_impl.cc
- cloud/db_cloud_test.cc
- cloud/manifest_reader.cc
- cloud/purge.cc
- cloud/remote_compaction_test.cc
- db/db_test_util.cc
- db/db_test_util.h
- include/rocksdb/cloud/cloud_env_options.h
- Remove the use of AwsEnv from most of the public API.  This will make it easier to use alternative implementations in a later PR
- Change the use of CloudEnv::info_log_.  This change will allow this value to be removed/changed from the public API (it should be part of the Options, not the CloudEnv itself)
- Add GetStorageProvider() API to simplify calls
- Moved the methods for DbId from AwsEnv to CloudEnvImpl.  This change makes CloudEnvImpl a concrete class and moves all of the standard functions to CloudEnvImpl.  AwsEnv deals only with AWS-specific code.
> Multiple Code Cleanups

- CMakeLists.txt
- cloud/cloud_env_impl.cc
- cloud/cloud_env_impl.h
- cloud/cloud_file_cache.cc
- cloud/db_cloud_test.cc
- include/rocksdb/cloud/cloud_env_options.h
- src.mk
Summary:
Prior to this commit, you can either have all sst files in
cloud storage (which is the default) or you can have all sst files
cached in local storage (by setting keep_local_sst_files = true).
Add a CloudEnvOption sst_file_cache that uses an LRU to
cache sst files in local storage. The default setting for
sst_file_cache is null, which disables any new behaviour.
An sst file is cached in its entirety in local storage if needed.
This does not cache specific blocks of an sst file. This feature does
not cache any non-sst file (e.g logfile, manifest, etc ) at all.
1. The Get or a Scan request on the database generates a random read
request on the sst file and such a request causes the sst file to
be inserted into the local file cache. The assumtion is that sst files
that are used for …
> Add support to use a LRU cache to keep sst files on local storage.

- cloud/cloud_env_impl.cc
- cloud/cloud_file_cache.cc
- cloud/cloud_scheduler_test.cc
- cloud/cloud_storage_provider.cc
- include/rocksdb/cloud/cloud_env_options.h
The other changes are cosmetic and are done by clang lint fixes.
> Fixed initialization of sst_file_cache in the CloudEnvOptions construtor

- cloud/cloud_env_impl.cc
- cloud/cloud_env_impl.h
- cloud/cloud_file_cache.cc
- cloud/db_cloud_test.cc
- include/rocksdb/cloud/cloud_env_options.h
This allows dynamically enabling the sst file cache on a running db  by setting its size.
> If the sst_file_cache size is zero, then consider it to be disabled.

- db/db_impl/db_impl.cc
- include/rocksdb/options.h
- options/db_options.cc
- options/db_options.h
Writing options file is incredibly expensive, taking most CPU time when RocksDB workload creates many column families. This PR adds an option to turn off the options file. No behavior changes in the default setting.
> Add use_options_file option

- cloud/examples/clone_example.cc
- cloud/examples/cloud_dump.cc
- cloud/examples/cloud_durable_example.cc
The `clone_example.cc` and other cloud examples could not be run as the AWS credentials were not setup. Not sure why they work before.
> add aws init for cloud examples

- cloud/cloud_file_cache.cc
Cache::GetUsage and Cache::GetCapacity return a size_t type. This is then
being converted to a long when a uint64_t is expected by the Log() call.
Fix: Change type from long to unit64_t so a vanilla "make" call works.
> Fix DEBUG build error due to long -> unsigned long long conversion

- db/version_set.cc
- include/rocksdb/options.h
- options/db_options.cc
- options/db_options.h
- options/options_helper.cc
- options/options_settable_test.cc
For our use case syncing the MANIFEST file is not important, while
adding a big performance overhead. This new option allows us to disable
manfiest sync.
> Introduce new DBOption disable_manifest_sync

- db/external_sst_file_ingestion_job.cc
- include/rocksdb/options.h
- include/rocksdb/sst_file_writer.h
- table/sst_file_writer.cc
We don't need to fsync the file on close in our use case and syncing is
adding a considerable performance overhead. This commit introduces a
parameter unsafe_disable_sync that lets us disable the file sync.
> Introduce unsafe_disable_sync parameter in ingest external files

- cloud/aws/aws_s3.cc
- cloud/cloud_env.cc
- cloud/cloud_env_options.cc
- cloud/db_cloud_test.cc
- include/rocksdb/cloud/cloud_env_options.h
If the option is set to true (and use_aws_transfer_manager is false), we
will use direct IO to download S3 files.
Written by igorcanadi, commandeered by nbronson
> Introduce CloudEnvOptions::use_direct_io_for_cloud_download

- cloud/aws/aws_s3.cc
- include/rocksdb/cloud/cloud_env_options.h
Summary:
This diff adds CloudEnvOptions::s3_client_factory, which gives
callers the ability to manage the full S3Client lifecycle.
Test Plan:
1. rocksdb cloud compiles
2. rockset internal E2E tests pass
> add S3Client factory as a config option

- db/version_set.cc
- utilities/blob_db/blob_db_test.cc
- utilities/transactions/write_prepared_transaction_test.cc
This reverts commit f89423a57a78e28de68c9a618a6e5f2f00ec5270.
See my comment here for the explanation:
https://github.com/facebook/rocksdb/pull/8438#issuecomment-1005603929.
This change is causing problems in our production environment.
> Revert "Snapshot release triggered compaction without multiple tombstones (#8357)"

- cloud/cloud_storage_provider.cc
It is possible that `DoGetCloudObject()` suceeds, but the local file is not
successfully created. In that case `GetCloudObject()` would return
`Status::NotFound`, wihch is incorrect, as higher levels of the code assume
`NotFound` to mean the file is not present in the cloud.
This PR fixes this.
> Fix GetCloudObject return status

- cloud/aws/aws_s3.cc
- cloud/cloud_env_impl.cc
- cloud/cloud_env_impl.h
- cloud/cloud_manifest.cc
- cloud/db_cloud_impl.cc
- cloud/db_cloud_test.cc
- include/rocksdb/cloud/cloud_env_options.h
This PR improves the DB initialization in several ways:
* Detecting if the database is new is handled explicitly in `DBCloud::Open()`.
Previously, low-level methods such as `CloudEnvImpl::RollNewEpoch()` handled
new database creation. `RollNewEpoch()` is no longer called for new databases.
* No automatic migration from non-cloud RocksDB. Migration is now executed
explicitly through `CloudEnv::MigrateFromPureRocksDB()`. This simplifies the
initialization when migration from RocksDB is not necessary and reduces its
surface area.
* CLOUDMANIFEST is created explicitly in `DBCloud::Open()` if it's not found.
It is uploaded to the cloud after `DB::Open()`, which means the cloud
database will never be left in an inconsistent state where CLOUDMANIFEST
exists, but MANIFEST doesn't. In the cloud, …
> Improve DB initalization

- CMakeLists.txt
- Makefile
- cloud/filename.h
- cloud/replication_test.cc
- db/db_impl/db_impl.cc
- db/db_impl/db_impl.h
- db/db_impl/db_impl_compaction_flush.cc
- db/db_impl/db_impl_debug.cc
- db/db_impl/db_impl_open.cc
- db/db_impl/db_impl_write.cc
- db/flush_job.cc
- db/memtable.h
- db/version_edit.cc
- db/version_edit.h
- db/version_edit_handler.cc
- db/version_set.cc
- db/version_set.h
- db/write_batch.cc
- db/write_batch_internal.h
- include/rocksdb/db.h
- include/rocksdb/options.h
- include/rocksdb/utilities/stackable_db.h
- include/rocksdb/write_batch.h
- options/db_options.cc
- options/db_options.h
- src.mk
This PR implements phyiscal replication in RocksDB. It introduces a
`ReplicationLogListener`, which receives replication log events on the leader
and `DB::ApplyReplicationLogRecord()`, which applies those records on the
follower(s).
Consult the code comments and internal design doc for more details.
Introduced a new replication_test
> [SYS-2483] Physical Replication in RocksDB

- cloud/cloud_env_impl.cc
- cloud/cloud_env_options.cc
- include/rocksdb/cloud/cloud_env_options.h
Follower in physical replication shouldn't roll cloud manifest epoch on open.
Otherwise, it can't find the files that the leader created. This PR adds an
option that lets us skip epoch roll on startup.
This code will change in the future when we start propagating CLOUDMANIFEST
updates in the replication log, which is why I'm marking the option as
experimental.
> [SYS-2483] Add an option to not roll cloud manifest on startup

- cloud/replication_test.cc
`state_ = TAILING` always returns true.
> Use == instead = for assertion check

- cloud/cloud_env_impl.cc
Apparently, it's possible that we pass a null cloud_manifest_ when calling `RemapFilename`. So we need to assert cloud_manifest only if necessary.
> assert cloud_manifest when necessary

- CMakeLists.txt
- cloud/replication_test.cc
- db/db_impl/db_impl.cc
- db/db_impl/db_impl.h
- db/db_impl/db_impl_compaction_flush.cc
- db/db_impl/db_impl_debug.cc
- db/db_impl/db_impl_write.cc
- db/db_impl/replication_codec.cc
- db/db_impl/replication_codec.h
- db/memtable_list.h
- include/rocksdb/db.h
- include/rocksdb/options.h
- include/rocksdb/utilities/stackable_db.h
- src.mk
Fixed multiple bugs related to memtable switch replication:
1. We don't use WAL, so all the switched memtables have the same next_log_num set. This can be an issue with physical replication.
2. We should pass `replication_sequence` and `next_log_num` with `kMemtableSwitch`. Detailed reason described in #SYS-2546
3. For our case, there is no need to create WAL when bumping `next_log_num`. removing that as well
> [SYS-2536] Fix memtable switch replication bug

- db/version_set.cc
We need this to allow downgrading a RocksDB-Cloud from a leader-follower mode to a legacy mode.
> Allow manifest records without update sequence on the follower

- util/user_comparator_wrapper.h
This reverts commit 719ea519749788b9782b033fa8f60ac215756d73.
I saw a few compilation errors with the commit:
```
In file included from ./db/arena_wrapped_db_iter.h:14,
from db/arena_wrapped_db_iter.cc:10:
./db/db_iter.h: In member function 'void rocksdb::DBIter::LocalStatistics::BumpGlobalStatistics(rocksdb::Statistics*)':
./db/db_iter.h:97:24: error: 'iter_read_bytes' was not declared in this scope
97 |       PERF_COUNTER_ADD(iter_read_bytes, bytes_read_);
|                        ^~~~~~~~~~~~~~~
./db/db_iter.h:97:7: error: 'PERF_COUNTER_ADD' was not declared in this scope
97 |       PERF_COUNTER_ADD(iter_read_bytes, bytes_read_);
|       ^~~~~~~~~~~~~~~~
```
Also, I'll update the branch protection rules for this repo.
> Revert "Disable user_key_comparison_count stat"

- util/user_comparator_wrapper.h
We don't use the stat, and accessing thread local storage is expensive
Kicking off a new rockset build against this commit to make sure everything compiles: https://buildkite.com/rockset/build-everything/builds/59433
> Disable user_key_comparison_count stat

- cloud/replication_test.cc
- db/db_impl/db_impl.cc
- db/db_impl/db_impl.h
- include/rocksdb/db.h
- include/rocksdb/utilities/stackable_db.h
We need this information in leader-follower protocol. Followers need to know if
the manifest they have locally is recent enough or if they need to fetch a new
one from the cloud.
> Expose ManifestUpdateSequence in public DB API

- cloud/cloud_env_impl.cc
- cloud/cloud_env_impl.h
- cloud/cloud_env_wrapper.h
- cloud/db_cloud_test.cc
- cloud/manifest_reader.cc
- cloud/manifest_reader.h
- db/version_set.h
- include/rocksdb/cloud/cloud_env_options.h
We changed the API of finding live files based on cloud manifest. 
We need to specify the bucket from which to find live files. It read the cloud manifest and manifest from s3 directly with the range call api.
But this can be slow for large manifest files.
`FindLiveFiles` will pull manifest from s3 directly if not exists locally.
Now to list all live files for cloudmanifest in s3, we need to:
```
cloud_env->PreloadCloudManifest(local_dbname);  // fetch cloud manifest to local and load it into cloud_env
cloud_env->FindLiveFiles(local_dbname, &file_nums, &manifest); // find live files based on local manifest(which is fetched from s3 if not exists)
```
Of course, it assumes that `cloud_manifest` is not updated after loading.
> Find live files based on local manifest files

- cloud/db_cloud_test.cc
The `CloudTest.FileCacheOnDemand` test is flaky. We created 2 shards for the lrucache, and total capacity = 3000 bytes. So each shard got 1500 capacity. In the most unlucky case, all 4 sst files might fall into one shard, and each sst file ~ 887bytes, so we ended up with only 1 sst file locally(one shard has 1500 capacity, so it can only hold one sst file). The fix is easy, we only allocated 1 shard for the lrucache.
> Fix flaky test CloudTest.FileCacheOnDemand

- cloud/aws/aws_s3.cc
- cloud/cloud_env_impl.cc
- cloud/cloud_env_impl.h
- cloud/cloud_env_wrapper.h
- cloud/cloud_storage_provider.cc
- cloud/cloud_storage_provider_impl.h
- cloud/db_cloud_test.cc
- cloud/manifest_reader.cc
- cloud/manifest_reader.h
- include/rocksdb/cloud/cloud_env_options.h
When finding all the live files based on manifest files, we would like to get the version(in s3) of the Manifest file we read from. Motivation behind this is, if a compaction happened after listing live files and before data copy, the version of Manifest file we read when copying the files would be inconsistent with the list of live sst files.
The way we achieve that is, if we ask for the manifest file version, we fetch the latest manfiest file from s3 and manifest file version. I added a separate API: `FindAllLiveFilesAndFetchManifest` in `CloudEnv` for this, since if we mistakenly called this function with a running db, it would override the local Manifest file with latest Manifest file in s3, which could potentially cause issue. Added a separate API here to make sure the user of this …
> Return manifest file version when finding live files

- db/db_impl/replication_codec.cc
There is no need to include the version number here. If we want to change the format while maintaining backwards compatibility, we can always add another record type.
> Remove version number from serialized mem switch record

- cloud/db_cloud_test.cc
Fixed two tests broken by this [PR](https://github.com/rockset/rocksdb-cloud/pull/180).  These two tests assume that when `srcBucket != dstBucket` (i.e., durable in rockset), we should `resync_on_open=true`. The other tests don't have this assumption.
> Fix tests assuming resync_on_open = true

- cloud/cloud_manifest.cc
- cloud/cloud_manifest.h
- tools/ldb_cmd.cc
- tools/ldb_cmd_impl.h
- tools/ldb_tool.cc
Made ldb to support dumping CLOUDMANIFEST
Example:
```
> ldb cloud_manifest_dump --path=CLOUDMANIFEST --verbose
Past Epochs: [
(6, b4646dd83efb0cca),
(12, 475afd2ff65ef56d),
(16, d4490aa2f445463f),
(21, b519e29a1bc838ed),
...
(3265, 3643e39f9255b8d1),
(3268, 9540f3f4009ae956),
(3271, 85de60a55896cf47),
(3275, bf4f896b7e402052),
]
Current Epoch: e8ab9866fb2973f2
```
> CLOUDMANIFEST dumper

- cloud/aws/aws_s3.cc
- cloud/cloud_env_impl.cc
I believe each of these are situation which would be an error with plain old rocksdb, but rocksdb treats it as a case where we need to reinitialize our local directory. Let's not spam the logs with scary red and yellow stuff when this is perfectly benign.
> Reduce severity levels of some misleading logs

- cloud/cloud_env_impl.cc
- cloud/cloud_env_impl.h
- cloud/cloud_env_options.cc
- cloud/db_cloud_impl.cc
- cloud/db_cloud_test.cc
- include/rocksdb/cloud/cloud_env_options.h
Added `new_cookie_on_open` option in cloud_env, so that we can switch to new cookie when we open db and roll new epoch. This is a temporary option so that we can roll out stage 1 of leader follower.
Also, removed option: `upload_cloud_manifest_without_cookie_suffix`, which was originally used to make sure we can roll back to empty cookie. But `new_cookie_on_open` can achieve similar things.
> Switch CLOUDMANIFEST on db open

- cloud/db_cloud_impl.cc
With the current implementation it is possible that the MANIFEST and CLOUDMANIFEST are uploaded to s3 before all sst files.
> Making checkpoint to cloud upload MANIFEST and CLOUDMANIFEST only after uploading all SST files

- cloud/cloud_scheduler.cc
- cloud/cloud_scheduler_test.cc
There were multiple races of `LocalCloudScheduler` implementation:
- `job_mutex_` wasn't locked when canceling jobs in `~LocalCloudScheduler`. Therefore, it's possible that right before we started canceling job in destructor, the job was erased when execution is done
- Job execution callback accessed the`jobs_` and `job_mutex_`  even after `~LocalCloudScheduler` is called.
> [SYS-2143] Fix race between LocalCloudScheduler destruction and job rase after execution

- db/db_flush_test.cc
- db/db_impl/db_impl.cc
- db/db_impl/db_impl.h
- db/db_impl/db_impl_compaction_flush.cc
- db/db_impl/db_impl_write.cc
- db/db_test.cc
- db/memtable.cc
- db/memtable.h
- include/rocksdb/db.h
- include/rocksdb/options.h
- include/rocksdb/utilities/stackable_db.h
- options/db_options.cc
- options/db_options.h
Flush could be triggered in following scenarios:
1. Single memtable exceeds `write_buffer_size` limit.  The memtable will be put into the flush scheduler queue, and flush is scheduled on next write.
2. All memtables exceed `db_write_buffer_size` limit. Memtables will be flushed right away
3. WAL size exceeds `max_total_wal_size`. Memtables will be flushed right away.
4. Manual flush
`FlushSwitch` allows us to enable flush if flush is disabled when opening db. All above four cases will be included (even though we only need 1 and 4)
I didn't support disabling flush on running db intentionally, since we don't need that right now. In leader/follower, db by default opens in follower mode with flush disabled. When follower tries to take over, it will enable flush. When a leader tries to become …
> [SYS-2941] Added FlushSwitch to allow turning on flush if disabled initially

- cloud/cloud_env_impl.cc
- cloud/cloud_env_impl.h
- cloud/cloud_scheduler.cc
- cloud/db_cloud_test.cc
- cloud/filename.h
There are two major changes in this PR:
* Clean up obsolete CLOUDMANIFEST files when opening db (not readonly, dest bucket set). _Before this PR, only MANIFEST files and sst files are cleaned up._
* Trigger the file deletion jobs before we roll the new epoch and only cleanup `CM/M/SST` files which don't belong to `cookie_on_open`. Therefore, neither the newly generated `CLOUDMANIFEST-new_cookie/MANIFEST-new_epoch` files nor `CLOUDMANIFEST-old_cookie/MANIFEST-old_epoch files` will be deleted. _Before this PR, `MANIFEST-old_epoch` files will be deleted as well_ . This change makes sure that two concurrent writers can keep running without intervening each other. If there are more than two concurrent writers, the latest two can keep running while the other writers' CM/M files will be deleted …
> [SYS-3094] clean up old CLOUDMANIFEST files

- cloud/cloud_scheduler.cc
`TEST_SYNC_POINT_CALLBACK` is empty and optimized away when building in `DEBUG_LEVEL=0`, which causes the `job_erased` variable to be unused.
> Fix variable 'job_erased' set but not used error

- cloud/cloud_env_impl.cc
- cloud/cloud_env_impl.h
- cloud/cloud_scheduler.cc
- cloud/cloud_scheduler.h
- cloud/cloud_scheduler_test.cc
- cloud/db_cloud_test.cc
We shouldn't delete `CLOUDMANIFEST-new_cookie` file when db is opened. Otherwise, if there exists some `CLOUDMANIFEST-new_cookie` file in s3, the file deletion job will be scheduled, which causes the `CLOUDMANIFEST-new_cookie` to be deleted after db is opened with `new_cookie`. For example, this can happen when we switch to empty cookie.
Also, empty cookie is a special cookie value in our system, which we will reuse to open db sometimes later. So just in case something is wrong, we don't delete empty `CLOUDMANIFEST` either. We can remove this assumption once we fully move to L/F. 
Also fixed a bug in `LocalCloudScheduler`, in which the scheduled jobs are never erased from the jobs list.
> [SYS-3140] don't delete CLOUDMANIFEST and CLOUDMANIFEST-new_cookie

- cloud/cloud_env_impl.cc
- cloud/cloud_env_impl.h
- cloud/db_cloud_test.cc
- include/rocksdb/cloud/cloud_env_options.h
Forcing MANIFEST resync when db is opened with `resync_on_open=True`. I added one extra temporary option: `resync_manifest_on_open` so that we can control this with sitevar and quickly rollback if we want to.
Reason why we want to do this now is to avoid following issue:
```
open durable (epoch = 1)
open ephemeral (epoch = 1, new_epoch=?)
durable delete sst-file
reopen ephemeral (epoch = 1, new_epoch=?), it reuses local manifest-1 file which still references the deleted sst-file
```
This happens after my recent file deletion [PR](https://github.com/rockset/rocksdb-cloud/pull/195), which doesn't cleanup `MANIFEST-old_epoch` when db is opened. 
I think we shouldn't rely on the assumption that local db is cleaned up correctly before opening db (e.g., what if the process gets interrupted …
> [SYS-3153] resync MANIFEST on db open

- cloud/cloud_env_impl.cc
- cloud/cloud_env_impl.h
- db/db_impl/db_impl.h
- db/db_impl/db_impl_open.cc
- db/db_test.cc
- include/rocksdb/cloud/cloud_env_options.h
- include/rocksdb/db.h
- include/rocksdb/options.h
- include/rocksdb/utilities/stackable_db.h
Couple of minor refactoring:
- Declare the cloud manifest switch related functions in `DB` since we would need to access them outside of rocksdb (e.g., during taking over)
- Make sure flush can only be turned on through `db->TurnOnFlush` but not through `dboptions.flush_switch`. This doesn't matter quite much for now. But if we want to support disabling flush on running db in the future, we would have to do it through `db`.
> Declare cloud manifest switch related functions in class DB

- cloud/replication_test.cc
- db/column_family.cc
- db/db_flush_test.cc
- db/db_impl/db_impl.cc
- db/db_impl/db_impl.h
- db/db_impl/db_impl_compaction_flush.cc
- db/db_impl/db_impl_open.cc
- db/db_impl/db_impl_write.cc
- db/db_test.cc
- db/memtable.cc
- db/memtable.h
- include/rocksdb/db.h
- include/rocksdb/options.h
- include/rocksdb/utilities/stackable_db.h
- options/cf_options.cc
- options/cf_options.h
- options/db_options.cc
- options/db_options.h
- options/options.cc
- options/options_helper.cc
- options/options_test.cc
Enabling/disabling auto flush through the `SetOptions` API and removed `FlushSwitch`. 
Flush could be triggered in following scenarios:
1. Single memtable exceeds `write_buffer_size` limit.  The memtable will be put into the flush scheduler queue, and flush is scheduled on next write.
2. All memtables exceed `db_write_buffer_size` limit. Memtables will be flushed right away. This is controlled through `WriteBufferManager`. 
3. WAL size exceeds `max_total_wal_size`. Memtables will be flushed right away.
4. Manual flush
When auto flush is disabled, 1 and 3 won't be triggered while 2 and 4 can still be issued. 
I didn't support disabling flush on running db intentionally, since we don't need that right now. In leader/follower, db by default opens in follower mode with flush disabled. When …
> Enable flush through the SetOptions API

- cloud/cloud_env_impl.cc
- cloud/db_cloud_test.cc
- db/db_test.cc
Local directory cleaning up during sanitization fails if there is directory locally. We changed the behavior here so that:
* Local directories are ignored
* File deletion errors are ignored as well. This is ok since we fetch the latest CM/M from s3 when `resync_on_open=True`
> [SYS-3275] Igore directories and errors during local directory cleaning up

- db/column_family.cc
- options/cf_options.cc
- options/options.cc
Logged `disable_auto_flush` options on start up correctly. Also, added logging of superversion version to help debug the issue of `EnableAutoFlush` called multiple times.
> Fix logging for disable_auto_flush

- db/column_family.cc
- db/db_flush_test.cc
- db/memtable.cc
- db/memtable.h
If compaction is started before we enable auto flush and finishes after we enable auto flush, we will hit the issue of trying to set `disable_auto_flush=true` when compaction job tries to install super version with the old mutable_cf_option.
Sequence of steps:
- Compaction starts with own copy of `mutable_cf_options`(`disable_auto_flush=true`)
- `SetOptions()` with `disable_auto_flush=false`
- Compaction finishes and calls `InstallSuperVersion` with `mutable_cf_options`(`disable_auto_flush=true`).
This seems to be a bug of rocksdb in general. A compaction job which is started with old `mutable_cf_options` and before we call `SetOptions` explicitly might install a super version with stale `mutable_cf_options`. I believe we can trigger the same bug for the other options as well. For the …
> [SYS-3282] InstallSuperVersion with old mutable_cf_options shouldn't trigger EnableAutoFlush

- cloud/cloud_env_impl.cc
- cloud/cloud_env_options.cc
In particular, don't print them in ValidateOptions() as that is invoked once
for every column family and it gets fairly verbose and not very useful.
> Unify the way cloud_env_options are printed

- db/db_impl/db_impl.cc
- db/db_impl/db_impl.h
- db/version_edit.h
- include/rocksdb/db.h
- include/rocksdb/utilities/stackable_db.h
This PR introduces debug logging on the follower. kMemtableSwitch and
kManifestWrite events are logged, which correspond to flush/compaction/column
family deletion and creation. All of those are logged on the leader as well, so
there is no concern of excessive logging.
DB::GetReplicationRecordDebugString is also introduced in the PR, which
provides much more detailed information about each replication event and could
be used when more verbose information is needed.
Log example:
```
2022/10/05-15:46:22.272607 140138908816064 [/db_impl/db_impl.cc:1195] Applying memtable switch with next log file: 1132, replication sequence (hex): 3534333438
2022/10/05-15:46:22.272617 140138908816064 [/db_impl/db_impl_write.cc:2012] [cf0] New memtable created with log file: #1132. Immutable memtables: 0. …
```
> [SYS-2547] Add replication debug logging to the follower

- cloud/replication_test.cc
- db/db_impl/db_impl.cc
- db/db_impl/db_impl.h
- db/db_test.cc
- include/rocksdb/db.h
- include/rocksdb/utilities/stackable_db.h
Until now, we created the ColumnFamilyOptions for a column family created
through ApplyReplicationLogRecord() by copying the default CF's options. This
was good enough for a prototype, but we need the ability on the caller to
provide the custom options. This PR implements the support through a
CFOptionsFactory callback provided to ApplyReplicationLogRecord().
> [SYS-3326] The caller should provide CF options for new CF in ApplyReplicationLogRecord

- memory/jemalloc_nodump_allocator.cc
- memory/jemalloc_nodump_allocator.h
- memory/memory_allocator.h
- memory/memory_allocator_test.cc
Calling `malloc_usable_size` on memory allocated from jemalloc arenas will cause asan to complain with `AddressSanitizer: attempting to call malloc_usable_size() for pointer which is not owned` error. This PR fixes the issue:
* In `JemallocNodumpAllocator`, uses `sallocx` and `nallocx` to return size for memory allocated from jemalloc.
Related issues:
* https://github.com/facebook/rocksdb/issues/10797
> Do not call malloc_usable_size on memory allocated from arenas

- db/version_set.cc
`new_manifest_on_next_update_.exchange()` is not executed if other conditions
for creating new manifest file are satisfied. This is not the behavior we want
- if the new manifest is created for any other reason, we don't need to create
the manifest again.
> Don't create a new manifest twice

- cloud/replication_test.cc
- db/db_impl/db_impl.cc
- db/version_set.h
The way we handled NextFileNumber propagation in ApplyReplicationLogRecord()
was broken. We only updated `next_file_number_` through
`versions_->MarkFileNumberUsed(e.GetLogNumber());`, when the version edit had the
`GetLogNumber()` present. Version edit's next file number (that was set on the
leader) was reset in follower's VersionSet based on the latest value of
`next_file_number_` here:
https://github.com/rockset/rocksdb-cloud/blob/27dbc089b8952fdda6203c190867526ab28a8a74/db/version_set.cc#L4911
This PR fixes this by setting `next_file_number_` when version edit received
from the leader carries the NextFileNumber. This should keep the
`next_file_number_` on the follower the same as on the leader.
A failing unit test is introduced and fixed in this PR.
> [SYS-3320] Fix the way NextFileNumbers are handled in ApplyReplicationLogRecord()

- cloud/db_cloud_impl.cc
- cloud/db_cloud_test.cc
See internal task for more information. Creating a new CLOUDMANIFEST with the
new cookie on open is equivalent to rolling a new cloud manifest. Therefore, we
shouldn't do it if `roll_cloud_manifest_on_open` is false.
Existing unit tests and internal buildkite tests.
> [SYS-3469] Don't create a new CLOUDMANIFEST if roll_cloud_manifest_on_open=false

- CMakeLists.txt
- cloud/cloud_env_impl.cc
- cloud/cloud_env_impl.h
- cloud/cloud_file_deletion_scheduler.cc
- cloud/cloud_file_deletion_scheduler.h
- cloud/db_cloud_test.cc
- src.mk
There is a race between `CloudEnv` destruction and cloud file deletion for current implementation:
* When CloudEnvImpl is destructed, it will acquire files_to_delete_mutex_ and  cancel existing jobs.
* While canceling existing jobs, it will wait (condition variable) if the job is still running.
* For the job that deletes files from cloud, it will try to acquire files_to_delete_mutex_ before actually deleting the files, therefore causing deadlock
We shouldn't acquire mutex in destructor. Also, it's possible that when the scheduled jobs are executed, `CloudEnv` might have already been destructed. Fixed above two issues by moving the file deletion scheduling into a separate class: `CloudFileDeletionScheduler` and only allow accessing it through a shared_ptr. In the scheduled jobs, it will …
> [SYS-3456] fix the race between CloudEnv destruction and file deletion

- cloud/cloud_file_deletion_scheduler.h
- cloud/replication_test.cc
- db/db_impl/db_impl.cc
The bug was that we called InstallSuperVersion() before RemoveOldMemTables(),
which means our newly installed superversion still had a pointer to an old
memtable. This means that each column family held onto exactly 1 memtable more
than it needs to, which explains the increased memory usage on the follower.
This is especially pronounced when most column families latest memtables are
empty.
Also fixed a bug where we forgot to set CF as initialized, which is only ever
used for stats gathering, so it's not as serious.
Added a repro unit test that for both of the problems.
> [SYS-3423] Fix memory leak in phyiscal replication

- cloud/cloud_env_impl.cc
- cloud/cloud_manifest.cc
- cloud/cloud_manifest.h
- cloud/cloud_manifest_test.cc
- cloud/db_cloud_test.cc
- include/rocksdb/cloud/cloud_env_options.h
In leader follower world, it's possible to re-apply the old (filenum, epochs). Made `AddEpoch` function to be idempotent to support this case
> [SYS-3633] Make CloudManifest::AddEpoch idempotent

- cloud/cloud_env_impl.cc
- cloud/cloud_env_impl.h
- cloud/cloud_manifest.cc
- cloud/cloud_manifest.h
- cloud/cloud_manifest_test.cc
- cloud/db_cloud_test.cc
- include/rocksdb/cloud/cloud_env_options.h
Addressed Igor's comments: https://github.com/rockset/rocksdb-cloud/pull/222#discussion_r1022082457
We should return `Status::OK` and return additional information through the `bool* update_applied` argument for `ApplyCloudManifestDelta`.
Also, now that it's possible to have one filenum showing more than once in `CLOUDMANFIEST` with different epochs,  we should only check `filenum` is sorted in ascending order when loading CM from file.
> Make ApplyCloudManifestDelta idempotent for old epoch

- cloud/aws/aws_s3.cc
Summary:
https://github.com/aws/aws-sdk-cpp/commit/3878f0112eb73b9a174b5b7ee21bbea9a693ef4a changed the public API by removing default params from S3Client constructor:
```
S3Client(const Aws::Auth::AWSCredentials& credentials,
-                 const Aws::Client::ClientConfiguration& clientConfiguration = Aws::Client::ClientConfiguration(),
-                 Aws::Client::AWSAuthV4Signer::PayloadSigningPolicy signPayloads = Aws::Client::AWSAuthV4Signer::PayloadSigningPolicy::Never,
-                 bool useVirtualAddressing = true,
+                 const Aws::Client::ClientConfiguration& clientConfiguration,
+                 Aws::Client::AWSAuthV4Signer::PayloadSigningPolicy signPayloads,
+                 bool useVirtualAddressing,
Aws::S3::US_EAST_1_REGIONAL_ENDPOINT_OPTION …
```
> [SRE-2477] Make RocksDB-Cloud work with newer version of AWS SDK

- db/column_family.cc
- db/db_flush_test.cc
Make sure write controller won't stop writes when auto flush disabled. Otherwise this would cause deadlock, since auto flush is only triggered when there are memtable writes.
> [sys-3901] don't stop writes when auto flush disabled

- file/file_util.h
To make it available to the `FileSystem` and `RandomAccessFile` implementations.
> Propagate `fill_cache` to `IOOptions`

- cloud/cloud_file_system.cc
- cloud/db_cloud_test.cc
- cloud/remote_compaction_test.cc
- include/rocksdb/cloud/cloud_file_system.h
There is no method in the public RocksDb interfaces to create an Env based on both and `Env` and a `FileSystem`.
`NewCompositeEnv` from `env.h` only takes a `FileSystem`, and uses `Env::Default` for the other argument.
Used new method in existing tests
> Add method to create a `CompositeEnv` from `(env, fs)`

- db/column_family.cc
- db/db_flush_test.cc
- db/db_impl/db_impl.cc
- db/db_impl/db_impl.h
- db/db_impl/db_impl_debug.cc
- db/db_write_test.cc
- include/rocksdb/options.h
- options/cf_options.cc
- options/cf_options.h
- options/options.cc
- options/options_helper.cc
- options/options_test.cc
Added new mutable cf option: `disable_write_stall`. Once it's set as true, write stall won't be triggered. Also, if writes are already blocked by write stall, calling `setOptions` will unblock the writes.
To avoid the issue we discussed [here](https://rockset-io.slack.com/archives/C0394R37RM4/p1664442085445909?thread_ts=1664277522.453319&cid=C0394R37RM4), we have to check latest `mutable_cf_options_` when calculating the write stall condition.
> [sys-4035] Add mutable cf option to disable write stall

- db/db_write_test.cc
We checked the manifest update seq here, which needs `atomic_flush=true` and `replication_log_listener` enabled. But `pipelined write` is conflicted with atomic flush, so skipping this for pipelined write.
> skip DisableWriteStallNotWriteManifest for pipelined write

- tools/db_bench_tool.cc
ObjectLibrary::Register was removed in RocksDB 7.9.9. This change is needed to build db_bench.
> Change ObjectLibrary::Register to ObjectLibrary::AddFactory

- cloud/cloud_file_system_impl.cc
We see it continuously in logs, which is confusing while debugging. It isn't an error condition
> Make "SanitizeDirectory local directory cleanup needed" INFO log

- cloud/aws/aws_file_system.cc
- cloud/aws/aws_file_system.h
- cloud/cloud_file_system.cc
- cloud/db_cloud_test.cc
- cloud/remote_compaction_test.cc
- include/rocksdb/cloud/cloud_file_system.h
See https://linear.app/rockset/issue/SYS-4270/potential-memory-leak-of-remote-compactors
InitAPI must be called only once, not on every creation of an AwsEnv.
> [SYS-4270] Fix memory leak in AwsFileSystem

- db/column_family.cc
- db/db_flush_test.cc
- db/db_impl/db_impl_compaction_flush.cc
Summary:
A change was made in
https://github.com/rockset/rocksdb-cloud/commit/61152544166ecf9fd50f90ad190561e5b11ccf55
to avoid recalculating write stall condition is the conditions didn't
change. In RocksDB-Cloud, we have an additional disable_write_stall that
influences write stall conditions, so we need an additional check.
This PR additionally removes the revert of
https://github.com/rockset/rocksdb-cloud/commit/edda219fc3 in
RocksDB-Cloud. We should strive for a match with RocksDB as much as
possible, and we'll change our higher-level code to account for the
change in semantics.
Test Plan:
DBWriteTest.DisableWriteStall was actually broken, this PR fixes it.
Reviewers:
> [SYS-4401] Fix disable_write_stall

- db/db_flush_test.cc
- db/db_impl/db_impl_compaction_flush.cc
This was a feature from the upstream RocksDB that was hard to adapt to
in our upper layer code, so here we just disable it.
> [SYS-4401] Don't fail the flush if writes are stalled

- cloud/replication_test.cc
- db/db_impl/db_impl.cc
Make sure file number is consistent between leader and follower for memtable switch event. This is important since otherwise follower which takes over after memtable switch could potentially reuse existing file number to create new sst files. Currently we get around this issue since we limit max number of memtables to 2.
NOTE: even after this change, we can still run into inconsistent file number between leader and follower when a follower tries to roll manifest file after applying `kManifestWrite`. This will cause follower's next file number to be greater than leader's next file number. I think this is fine since:
1) next time we apply `kMemSwitch` or `kManifestWrite`, we will reset file number.
2) it's ok for manifest file to have the same file number as sst files
3) follower's file …
> [sys-4870] set next file num for memtable switch event on follower

- cloud/replication_test.cc
- db/db_impl/db_impl.cc
When a follower shard tries to recover based on local log, it's possible for it to apply memtable switch record with log number much smaller than `next_file_number`. We need to make sure `next_file_number` on follower shard doesn't go backwards for this case.
We don't have this issue for manifest write since if a manifest write has been applied (by checking manifest update sequence), we never apply it again.
> [sys-4870] make sure file number won't go backwards

- cache/lru_cache.cc
- cache/lru_cache.h
We noticed that sometimes evicted entries from lru list don't have the right `helper`. I guess this happens when an entry is freed while it's still in LRU list, so next time it's evicted it causes the sigsegv. 
I added the null check to make sure only evicted entries from lru list are freed. This will make it to crash earlier and easier to debug.
> [sys-4900] only entries evicted from lru list are freed

- cache/lru_cache.cc
- cache/lru_cache.h
Reverts rockset/rocksdb-cloud#255
It doesn't seem to be caused by freeing an lru handle while it's in the lru list.
> Revert "[sys-4900] only entries evicted from lru list are freed"

- cloud/replication_test.cc
- db/db_impl/db_impl.cc
- db/db_impl/db_impl.h
- db/db_test.cc
- include/rocksdb/db.h
- include/rocksdb/utilities/stackable_db.h
Added new parameter: `allow_new_manifest_write` to `ApplyReplicationEvents`. If it's false, new manifest writes after DB's manifest update sequence won't be applied. 
This is useful to help detect local log divergence without applying the extra manifest writes.
> [sys-4993] don't apply manifest writes if allow_new_manifest_write is false

- cloud/cloud_file_deletion_scheduler.cc
- cloud/cloud_file_deletion_scheduler.h
- cloud/cloud_file_system.cc
- cloud/cloud_file_system_impl.cc
- cloud/cloud_file_system_impl.h
- cloud/db_cloud_test.cc
- db/db_test_util.cc
- include/rocksdb/cloud/cloud_file_system.h
Changed `cloud_file_deletion_delay` to `std::optional`. If it's not set, instead of scheduling cloud file deletion on file deletion queue asynchronously, we delete the cloud files immediately. This is different from setting the value to 0, in which case, the file deletion is still scheduled asynchronously. 
Also did some minor cleanup:
> [sys-4675] Don't schedule file deletions if delay not set

- cloud/replication_test.cc
- db/db_impl/db_impl_compaction_flush.cc
- db/db_impl/db_impl_write.cc
There is no need to generate a memtable switch log record if there is no column families flushed.
> [sys-4478] don't generate mem switch for empty flush

- cloud/replication_test.cc
- db/db_impl/db_impl.cc
- db/db_impl/db_impl.h
- db/db_test.cc
- include/rocksdb/db.h
- include/rocksdb/utilities/stackable_db.h
Summary:
Follower in the physical replication runs file deletions turned off,
i.e. `disable_delete_obsolete_files_on_open` is true, since it has no
business in deleting files that it doesn't own. Unfortunately, when file
deletions are turned off, so are table cache evictions. This means table
cache grows forever (in case of max_open_files=-1 setting) and we never
delete data structures of files we no longer need.
This PR fixes the problem, hiden under AR_EVICT_OBSOLETE_FILES flag for
safer rollout (this flag will eventually be removed and the new behavior
will be the default).
We evict obsolete files on every manifest write. If there are some files
that are pinned by the live iterator, we won't evict the files on
iterator deletion. Instead, we will keep them around until the next
manifest …
> [SYS-4840] Evict obsolete files from table cache on the follower

- cloud/cloud_file_system_impl.cc
- cloud/db_cloud_test.cc
We should create the dummy CURRENT file atomically to avoid corrupted CURRENT file due to crash.
> [sys-5279] create current file atomically

- cloud/db_cloud_test.cc
The file deletion related tests in `db_cloud_test` assumes that files to be scheduled on `CloudScheduler`. Setting the file deletion delay to 0s to make sure that files are indeed scheduled on the scheduler and getting deleted immediately.
> deflake file deletion related tests

- cloud/filename.h
currently the code isManifest constructs a temp string just to do comparison, use a string piece instead
> [SYS-5571] Stop constructing string to check isManifest

- cloud/db_cloud_impl.cc
- cloud/db_cloud_test.cc
- include/rocksdb/cloud/cloud_file_system.h
If `DBOptions::create_if_missing` is false, don't create new cloud db.
> [sys-5310] DBCloud::Open respects db option create_if_missing

- table/block_based/data_block_hash_index.h
- util/string_util.h
Summary:
Previously, libstdc++ defined uint8_t when you included <string>. This is no longer the case for the libstdc++ included in g++-13, so explicit <cstdint> includes are needed in a few places.
Test Plan:
compiles
> [SYS-5630] add missing cstdint includes

- cloud/replication_test.cc
- db/db_impl/db_impl_write.cc
We should construct the fragmented range tombstones during memtable switch so that range delete works.
> fix range delete when  replication log enabled

- include/rocksdb/memory_allocator.h
- memory/jemalloc_nodump_allocator.cc
- memory/jemalloc_nodump_allocator.h
Summary:
RocksDB's jemalloc no-dump allocator (`NewJemallocNodumpAllocator()`) was using a single manual arena. This arena's lock contention could be very high when thread caching is disabled for RocksDB blocks (e.g., when using `MALLOC_CONF='tcache_max:4096'` and `rocksdb_block_size=16384`).
This PR changes the jemalloc no-dump allocator to use a configurable number of manual arenas. That number is required to be a power of two so we can avoid division. The allocator shards allocation requests randomly across those manual arenas.
Pull Request resolved: https://github.com/facebook/rocksdb/pull/11400
Test Plan:
- mysqld setup
- Branch: fb-mysql-8.0.28 (https://github.com/facebook/mysql-5.6/commit/653eba2e56cfba4eac0c851ac9a70b2da9607527)
- Build: `mysqlbuild.sh --clean --release`
- Set env …
> Shard JemallocNodumpAllocator (#11400) -- backport

- cloud/cloud_file_system_impl.h
Summary:
Each WAL file by default allocates 64KB buffer in which it holds pending
writes. Our use of RocksDB-Cloud doesn't utilize WALs, so this memory is
wasted. This PR sets the buffer size to 0 in
CloudFileSystemImpl::OptimizeForLogWrite.
Test Plan:
db_cloud_test
Reviewers:
> [SYS-5319] Don't allocate buffer for WALs in CloudFileSystem

- cloud/replication_test.cc
- db/compaction/compaction_job.cc
- db/db_impl/db_impl.cc
- db/flush_job.cc
- db/version_edit.h
- db/version_set.cc
- include/rocksdb/db.h
A new per-file entity called epoch number was introduced in v7.10, which is used to sort L0 files (previously sorted by largest_seqno).  We need to make sure this number matches in leader follower. This is quite tricky during leaf deploy.
1. leader is on new version while follower is on old version. This is fine actually. epoch number will just be skipped on follower
2. follower is on new version while leader is on old version. This is the tricky one and this entire PR is to deal with this case.
The hack we use is to make follower to ignore epoch number from leader but simply calculating the epoch number on the fly. There are two cases:
1. flush which generates L0 files. epoch number is allocated based on `next_epoch_number` of each CF. The L0 files are sorted based on `largest seqno`. …
> [sys-4816] handle rocksdb upgrade to 7.10 in backwards compatible way

- db/db_impl/db_impl.cc
The consistency check compares the replicated epoch number from leader against epoch number calculated based on existing files on followers. It's actually possible that the consistency check fails in following rare case: 
D as leader running on old rocksdb, E as follower running on new rocksdb. Then D is re-opened as leader on new rocksdb, during which we recover the epoch number on db open. During recovery, the epoch number calculated on D might be different from the epoch number on E. But we won't detect the inconsistency until the mismatched files are compacted, which may only happen a few hours/days later.
This is fine since E will resync manifest files when re-opened. And very likely shard reopen has already happened during latest leaf roll. But out of precaution, let's treat this as …
> [sys-4815] treat inconsistent epoch number as poison instead of corruption

- db/arena_wrapped_db_iter.h
- db/db_impl/db_impl.cc
- db/db_impl/db_impl.h
- db/db_iter.h
- db/db_iterator_test.cc
- db/db_test.cc
- include/rocksdb/db.h
- include/rocksdb/utilities/stackable_db.h
This commit adds utility to DB to extract a sequence number from a passed in
iterator, if possible.
> Allow snapshot sequence retrieval from db iterator

- cloud/cloud_file_system_impl.cc
- cloud/cloud_file_system_impl.h
- cloud/cloud_file_system_wrapper.h
- cloud/db_cloud_test.cc
- cloud/manifest_reader.cc
- cloud/manifest_reader.h
- include/rocksdb/cloud/cloud_file_system.h
This somewhat mirrors existing `FindAllLiveFiles`, but doesn't resolve manifest filename or fetch it from the cloud, making it somewhat safer (in return for the need to ensure the manifest is present) and more flexible as it can operate for example on a copy of the live manifest.
> Add method to extract live file list from local manifest

- cloud/cloud_file_system_impl.cc
- cloud/db_cloud_test.cc
- include/rocksdb/cloud/cloud_file_system.h
This option was a temporary option used to rollout manifest resync on shard open safely. It's ok to remove it now.
> [sys-3153] remove resync_manifest_on_open option

- db/db_impl/db_impl.cc
- db/memtable.cc
- include/rocksdb/db.h
- table/block_based/block_based_table_reader.cc
Summary:
Added a thread local boolean that lets us turn on advanced logging to
debug sequence number issues we've been observing.
Test Plan:
Internal testing
Reviewers:
> [SYS-6306] Add sequence number logging to RocksDb-Cloud

- cloud/aws/aws_s3.cc
- db/version_set.cc
A couple of minor problems in RocsDB-Cloud that surfaced while
trying to enable coroutines.
> [SYS-6354] Fix compilation issues.

- cloud/replication_test.cc
- db/db_impl/db_impl.cc
- db/db_impl/db_impl.h
- db/db_test.cc
- db/snapshot_impl.h
- include/rocksdb/db.h
- include/rocksdb/utilities/stackable_db.h
Summary:
SuperSnapshot is a combination of a snapshot and a super-version. They
fulfill the same goal as snapshots, i.e. provide a consistent view of
the database. However, unlike snapshots, they also pin the current
super-version (memtable, immutable memtable list and file LSM tree). In
that way they are similar to iterators, which also pin the current
super-version for the duration of their lifetime.
Test Plan:
Added a basic unit test.
Reviewers:
> Introduce SuperSnapshot

- db/snapshot_impl.h
Summary:
```
./db/snapshot_impl.h:55:1: error: class 'SuperVersion' was previously declared as a struct; this is valid, but may result in linker errors under the Microsoft C++ ABI [-Werror,-Wmismatched-tags]
```
Test Plan:
Reviewers:
> SuperVersion is a struct, not a class

- cloud/replication_test.cc
- db/db_impl/db_impl.cc
This PR contains a couple of improvements to SuperSnapshots
implementation, the major one being support for one more variant of
MultiGet (there are three total, we now support two).
> Support SuperSnapshots in one more variant of MultiGet

- cloud/cloud_file_system_impl.h
This is to help with #sys-6435, in which live mount replicas never purge local manifest files.
My plan is to call `DeleteLocalInvisibleFiles` after follower applies `kNewEpoch`.  This will delete both invisible MANIFEST and  CLOUDMANIFEST files. NOTE that there is only one single CLOUDMANFIEST file locally since we never override the one in local disk once it's loaded. Also It's ok to delete local CLOUDMANIFEST files with live db. We only read it when opening rocksdb.
> [sys-6435] make DeleteLocalInvisibleFiles public

- db/column_family.cc
- db/column_family.h
- db/db_properties_test.cc
- db/internal_stats.cc
- db/internal_stats.h
- db/version_set.cc
- db/version_set.h
- include/rocksdb/db.h
Summary:
We can use this to measure the compactdness of the LSM tree. Size of 0
means the LSM tree is fully compacted.
Test Plan:
db_properties_test
Reviewers:
> [SYS-6514] Introduce kLiveNonBottommostSstFilesSize statistic

- cloud/cloud_file_system_impl.h
- include/rocksdb/cloud/cloud_file_system.h
Follow up PR for https://github.com/rockset/rocksdb-cloud/pull/298. We have to define the function in `CloudFileSystem` so that services depending on rocksdb-cloud library can access it.
> [sys-6535] define DeleteLocalInvisibleFiles in CloudFileSystem

- cloud/aws/aws_file_system.cc
- cloud/aws/aws_file_system.h
- cloud/aws/aws_s3.cc
- cloud/cloud_file_deletion_scheduler.cc
- cloud/cloud_file_system.cc
- cloud/cloud_file_system_impl.cc
- cloud/cloud_file_system_test.cc
- cloud/cloud_storage_provider.cc
- cloud/db_cloud_impl.cc
- cloud/db_cloud_test.cc
- cloud/manifest_reader.cc
- cloud/purge.cc
- db/db_test_util.cc
- include/rocksdb/cloud/cloud_file_deletion_scheduler.h
- include/rocksdb/cloud/cloud_file_system_impl.h
- include/rocksdb/cloud/cloud_file_system_wrapper.h
- include/rocksdb/cloud/cloud_storage_provider_impl.h
So CloudFileSystemImpl et. al. can be extended from outside the tree
Test plan: it builds
> Move some header files from cloud/ to include/rocksdb/cloud/

- db/version_set.cc
- include/rocksdb/statistics.h
- monitoring/statistics.cc
Adding counters to record the number of times we do a read from an SST file while executing a MultiGet and the number of times we read files in sequence (a file read is waiting for another file read to complete). 
The point of this change is to gauge how much benefit one can get from increased MultiGet parallelism provided by the coroutine based async file reads.
> Add counters for SST File reads/blocks in MultiGet.

- CMakeLists.txt
- db/compaction/compaction_job_test.cc
- third-party/gtest-1.8.1/fused-src/gtest/gtest-all.cc
Changes in this PR:
CMakeList:
* Moved ${CMAKE_CXX_FLAGS} after -Wall to allow for turning off warnings from higher level directory.
* Removed referece to *remote_compaction* files that are not present in the repository.
A couple of small code changes to address compiler warnings.
> CMake Fixes

- cloud/aws/aws_file_system.cc
- cloud/cloud_file_system.cc
- cloud/cloud_file_system_impl.cc
- cloud/cloud_file_system_test.cc
- cloud/cloud_storage_provider.cc
- include/rocksdb/cloud/cloud_file_system.h
- include/rocksdb/cloud/cloud_file_system_impl.h
Splitting the CloudFileSystem class into a pure interface class
and a separate class that contains static initialization and factory
methods (CloudFileSystemEnv).
This will make it possible to provide other implementations of CloudFileSystem
wihtout having to wrangle with static functions and options.
> Clarify CloudFileSystem API.

- cloud/cloud_file_system.cc
- cloud/cloud_file_system_impl.cc
- cloud/db_cloud_impl.cc
- file/random_access_file_reader.cc
- file/random_access_file_reader.h
- include/rocksdb/cloud/cloud_file_system.h
- include/rocksdb/cloud/cloud_file_system_impl.h
- include/rocksdb/file_system.h
- util/async_file_reader.cc
- util/async_file_reader.h
Extending the file API to provide an option to implement asynchronous
multi read operation. The default implementation delegates to AsyncRead.
Updated the AsyncFileReader class implementation to use MultiReadAsync.
> [SYS-6179] Add MultiReadAsync file API.

- cloud/replication_test.cc
- db/db_impl/db_impl_compaction_flush.cc
Summary:
This was broken when resolving merge conflicts on RocksDB 8.9.1 upgrade.
Test Plan:
Added a unit test
Reviewers:
> [SYS-7306] Flush all column families when replication_log_listener exists

- cloud/replication_test.cc
- db/db_impl/db_impl.cc
- db/replication_epoch_edit.cc
- db/replication_epoch_edit.h
Usually `ReplicationEpochSet` covers all (epoch, first mus) after the persisted replication sequence. But it's possible that `ReplicationEpochSet` only covers the most recent `max_num_replication_epochs` if there are too many of them. This can happen for collections without active writes. Following corner case is possible:
* follower prunes replication epochs since there are too many of them
* follower is reopened, it will realize that there are (epoch, mus) < `ReplicationEpochSet` in local log, i.e, pruned (epoch,mus), so follower decides to cleanup local log and reopens db.
* follower reopens and starts to tail from leader, but leader's local log also contains these pruned (epoch, mus). There is no way that follower can recover from this without reopening leader.
The solution in this PR …
> [sys-7056] don't treat pruned (epoch,mus) as diverged

- table/multiget_context.h
Increasing the maximum batch size to improve IO performance during MultiGets.
> Increase MAX_BATCH_SIZE to 1024 for Multigets.

- CMakeLists.txt
Summary:
This linker flag does not seem to be needed, and prevents use of gold or lld at link time.
Test Plan:
* build using llvm thinLTO
> remove --copy-dt-needed-entries when linking exes

- cloud/cloud_file_system_impl.cc
- cloud/db_cloud_impl.cc
- cloud/filename.h
For azure blob store, "/a/b" is different from "/a//b", so we can't have any extra slashes.
> Remove extra slash for manifest file path

- cloud/purge.cc
Right now the purger loops forever without waiting for `purger_periodicity_millis` between two runs. That's a bug. Additionally, when the purger is stopped, it waits the configured periodicity (10 minutes by default) before stopping. This is a real problem when one wants to gracefully shut down a DB. 
This PR fixes it.
By toggling the precondition of `wait_for`, the purger now waits the right duration between two runs and shutdown on demand without waiting which is the intended behavior.
> fix(purger): Fix the purger loop

- db/db_test2.cc
- db/version_set.cc
- include/rocksdb/options.h
- options/db_options.cc
- options/db_options.h
With the leader follower replication + RocksDB Cloud, once there is io_error for manifest write, we shouldn't allow writing kManifestWrite record to local replication log and syncing manifest file anymore. Reason is, it's possible that replication log is closed after this, which causes following manifest writes to be synced but not showing up in replication log. What's more, they might use previous manifest write's manifest update sequence since manifest update sequence is not bumped on io error.
> Add the option of skipping manifest writes on first sync error

- db/column_family.cc
- db/db_impl/db_impl.cc
- db/db_test.cc
- env/env_basic_test.cc
- file/file_util.cc
Changes:
1) Current FileCopy will truncate the source file to zero bytes if source and target is same. The new behavior is it will do nothing when source and target is same. 
2) Skip the versions_->LogAndApply for extra two options: disable_auto_compactions, disable_auto_flush. These two options do not change the LSM state, so it's safe to do that.
> [MISC]Fix FileCopy  and add other options to skip versions_->LogAndApply

- options/db_options.cc
- options/options_helper.cc
Main fix here is to be able to build DBOptions from immutable db options for `attempt_recovery_after_manifest_write_error` and `max_num_replication_epochs`. We call function: `rocksdb::GetOptionsFromString` in rockset. So if the option is set before we call that function, the option could be reverted to default if we don't support building DBOptions from immutable db options here.
> Fix option attempt_recovery_after_manifest_write_error

- table/block_based/block_based_table_reader.cc
- table/block_based/block_based_table_reader.h
Rocksdb fetches full tail of the SST file on `BlockBasedTable::Open()` regardless of whether or not it actually needs to read the index and filter blocks. Normally this is fine, as these blocks are expected to be < 5MB [[link]](https://github.com/facebook/rocksdb/wiki/Partitioned-Index-Filters#how-large-are-the-indexfilter-blocks) -- but we have workloads where the filter blocks are very large. In this case it doesn't make sense to prefetch the full tail if we don't need to read the index/filter blocks at all.
This PR refactors some code to extract pinning info in a separate struct. We only read the index/filter blocks if `prefetch_all || preload_all || pining_enabled`; so this PR now does prefetch in two phases:
1. Only prefetch ~4KB (footer + properties)
2. Use the above to decide if …
> Only prefetch footer on db open

- env/env_encryption.cc
- env/env_test.cc
Rocksdb uses `FileSystemWrapper` class to create an `EncryptedFileSystem` -- this basically creates a shim over the base file-system with the de/encryption logic being executed in the shim layer.
This PR fixes (what I think is) a bug in the implementation where RocksDb uses uses a default env when calling `efs->PrepareOptions()`. This is all fine when the base FS is a Default PosixFS -- but fails catastrophically when the base FS is something else.
Added new unit test; fails before my change; passes after.
> [rocskdb-cloud] EncryptedFS should use correct base FS 

- db/db_impl/db_impl.cc
- db/db_impl/db_impl_secondary.cc
- db/memtable_list.cc
- db/memtable_list.h
Summary:
Add memtable dropping logs in RemoveOldMemTables. This is to provide evidence that memtable is released in follower properly.
> [diagnostics] add log for dropping memtable at follower
